### ISSUE TITLE
数字类型转换问题

### ISSUE THREAD

**Issue by WeiBanXian** [hlerenow/hSwiper#1]
component > hSwiper > hSwiper.js > 310行:
    `var index=this.nowView+1;`
    有时候会出现this.nowView转换数字类型失败
    改成如下即可：
    `var index=parseInt(this.nowView)+1;`

**Comment by hlerenow** [comment]
其实这是由于，你在调用插件接口方法时，传入了字符类型的index 可能导致，之前我设想的入参就应该是**Number** 类型，因为你使用 **getNowView()**  返回的 index 就是 **Number** 类型，但是我在文档里面没有明显的说明，不过现在我已经把 使用说明修改了， 代码顺便也兼容了，感谢提问 。
