### ISSUE TITLE
你好，我想问一下，我想支持滑动的时候可循环，应该怎么修改

### ISSUE THREAD

**Issue by AndriodStudent** [hlerenow/hSwiper#10]
你好，我想问一下，我想支持滑动的时候可循环，应该怎么修改

**Comment by hlerenow** [comment]
参考 https://github.com/hlerenow/hSwiper/issues/4

**Comment by hlerenow** [comment]
2.0 已经支持循环滚动，https://github.com/hlerenow/hSwiper
