### ISSUE TITLE
现在使用taro 想使用这个插件

### ISSUE THREAD

**Issue by bwcx-jzy** [hlerenow/hSwiper#11]
现在使用taro 想使用这个插件，由于不太熟悉这个，也不太了解这块，想请问一下作者能否提供一下转taro 的文档呢

**Comment by hlerenow** [comment]
不好意思哈，这个是微信小程序的原生插件，不支持转taro，如果想用的话，只能taro编译成微信小程序代码后，在编译后的代码里面使用，或者你参考下taro的官方文档集成下【https://nervjs.github.io/taro/docs/wx-third-party.html】

**Comment by bwcx-jzy** [comment]
那请问完整的组件包在哪个文件夹下：src/ ？

**Comment by bwcx-jzy** [comment]
刚开始使用，对组件这些还有些地方不太熟悉，还请赐教

**Comment by hlerenow** [comment]
npm 安装 ，安装后再node_modules 里面 找到，hswiper-wx文件下，miniprogram_dist文件家里面的就是完整的组件源码

**Comment by bwcx-jzy** [comment]
![image](https://user-images.githubusercontent.com/16408873/46777193-4476ba00-cd41-11e8-8ba2-318d2e19c676.png)

这样没有任何效果

**Comment by bwcx-jzy** [comment]
![image](https://user-images.githubusercontent.com/16408873/46777292-9c152580-cd41-11e8-8cb7-7737f49b5021.png)
编译后组件下没有子标签

**Comment by hlerenow** [comment]
![image](https://user-images.githubusercontent.com/13299648/46777303-a6cfba80-cd41-11e8-9933-9a82613acd0f.png)

这个文件夹放在项目根目录下和pages 同级
![image](https://user-images.githubusercontent.com/13299648/46777289-9b7c8f00-cd41-11e8-800e-980423079aa3.png)

**Comment by hlerenow** [comment]
![image](https://user-images.githubusercontent.com/13299648/46777363-d67ec280-cd41-11e8-8b46-fafd2a5175c7.png)
example里面的文件目录结构参考下

**Comment by hlerenow** [comment]
行吗？

**Comment by bwcx-jzy** [comment]
不行

**Comment by bwcx-jzy** [comment]
会不会是数据传递问题呢，taro 数据好像有点变化

**Comment by hlerenow** [comment]
[taro-接入.zip](https://github.com/hlerenow/hSwiper-wx/files/2467324/taro-.zip)
这个是taro 接入的demo 需要手动把 根目录下的hSwiper下的文件拷贝到 dist文件夹下面，也只能支持微信小程序使用

**Comment by hlerenow** [comment]
![image](https://user-images.githubusercontent.com/13299648/46780081-78f07300-cd4d-11e8-8fa1-3fe17d9f2d87.png)

可以参考这个，配置下，让taro 自己拷贝文件夹 https://nervjs.github.io/taro/docs/config-detail.html

**Comment by bwcx-jzy** [comment]
加了
![image](https://user-images.githubusercontent.com/16408873/46783533-3afb4b00-cd5d-11e8-9199-6c1c12a0f50a.png)

**Comment by bwcx-jzy** [comment]
![image](https://user-images.githubusercontent.com/16408873/46783718-ead0b880-cd5d-11e8-989e-63a4c8120e44.png)

**Comment by hlerenow** [comment]
有zip 包，上面，自己解压 ，安装npm 后跑一下，zip 是一额taro 工程能跑的。插件引入没？多检查检查
，在需要使用的页面配置，路径根据自己的路径适当修改
![image](https://user-images.githubusercontent.com/13299648/46784102-62531780-cd5f-11e8-85a3-e7480f9a5803.png)

**Comment by bwcx-jzy** [comment]
![image](https://user-images.githubusercontent.com/16408873/46784743-d7275100-cd61-11e8-98b4-ca0cfa138006.png)


![image](https://user-images.githubusercontent.com/16408873/46784821-2f5e5300-cd62-11e8-81c5-0c694db28e45.png)

**Comment by hlerenow** [comment]
这个就不知道了，你按照zip里面的方法引入是可以跑的， https://github.com/hlerenow/hSwiper-wx/files/2467324/taro-.zip。

**Comment by bwcx-jzy** [comment]
好的

**Comment by bwcx-jzy** [comment]
谢谢大佬
