### ISSUE TITLE
mpvue的应该如何使用此组件

### ISSUE THREAD

**Issue by blackcloud2333** [hlerenow/hSwiper#13]
1 小程序原生swiper真的做的像一堆辣鸡
2 能否在mpvue当中引入（个人尝试引入，暂未成功）
3 如果支持mpvue应该如何引入呢？

**Comment by hlerenow** [comment]
mpvue 支持 使用小程序组件吗？如果支持就可以使用。你引入过程报什么错？可以贴出来我帮你看看

**Comment by blackcloud2333** [comment]
1 小程序支持原生组件，但是原生组件太辣鸡了
2 mpvue当中的wxml部分
<swiper class="page-index__swiper" :class="{swiper: isIphonex}" @change="stopImage" @animationfinish="animationFinish" :previous-margin="previousMargin" :next-margin="nextMargin" :display-multiple-items="displayMultipleItems" :circular="circular"  :indicator-dots="indicatorDots" :autoplay="autoplay" :interval="interval" :duration="duration">
    <block v-for="(item, index) in goodsList" :key="index">
      <swiper-item class="slide-item"  @touchmove="specialShow">
        <image :src="item.listBannerUrl + '?t='+random" class="slide-image" lazy-load="true" @click="beryClick(item.goodsCode)"/>
        <div class="slide-wrapper">
          <div class="slide-doule-arrow" @click="showDetail(index)">
            <i class="iconfont icon-double-arrow"></i>
          </div>
        </div>
      </swiper-item>
    </block>
  </swiper>
===========================================================
<!--上面的是mpvue的使用例子，下面的是自己引入hswiper部分—->
<View style="width: 320px; height: 500px" class="swiper">
  <comp
:recycle="recyle"
vertical= false
templateName="hSwiperItem"
padding="30"
:moveTo="moveTo"
@customevent="getRef"
initIndex="2"
width="320"
height="500"
animationType="ease-out"
animationDuration="300"
@firstView="firstView"
@alreadyFirstView="alreadyFirstView"
@beforeViewChange="beforeViewChange"
@afterViewChange="afterViewChange"
@lastView="lastView"
@alreadyLastView="alreadyLastView"
@move="viewMove"
:dataList="goodsImage"
></comp>
</View>






export default {
name: 'index',
components: { goodsDetail, share },
data () {
return {
dataList: [
'http://statics.h-five.com/db2.jpg',
'http://statics.h-five.com/db3.jpg',
'http://statics.h-five.com/little-love.jpg',
'http://statics.h-five.com/withme.jpg'
],
dataList2: [0, 1, 2, 3, 4],
moveTo: 0,
recyle: false,

onReady () {
if (this.recyle) {
setInterval(() => {
this.moveTo = (this.moveTo + 1) % this.dataList.length
console.log('change view')
    }, 1000)
  }
},
alreadyFirstView (e) {
  console.log('alreadyFirstView', e)
},
firstView (e) {
  console.log('firstView', e)
},
beforeViewChange (e) {
  console.log('beforeViewChange', e)
},
afterViewChange (e) {
  console.log('afterViewChange', e)
},
lastView (e) {
  console.log('lastView', e)
},
alreadyLastView (e) {
  console.log('alreadyLastView', e)
},
viewMove (e) {
// console.log('viewMove', e)
},
   }
}
这个不是完整的代码，只是其中的一部分
mpvue引入第三方组件的方式和vue几乎是一模一样的，

**Comment by hlerenow** [comment]
今天有时间看了下，mpvue不支持第三方的小程序组件引入，抱歉。只支持小程序的原生组件使用，本地也跑了下，mpvue的编译过不了

**Comment by blackcloud2333** [comment]
好的，谢谢啦。
已经自己写了一个适合mpvue的自定义swiper 组件


| |
窦雅宁
|
|
yaningdou@163.com
|
签名由网易邮箱大师定制


在2018年12月25日 19:14，何雷<notifications@github.com> 写道：

今天有时间看了下，mpvue不支持第三方的小程序组件引入，抱歉。只支持小程序的原生组件使用，本地夜跑了下，mpvue的编译过不了
