### ISSUE TITLE
item点击事件怎么加

### ISSUE THREAD

**Issue by CharlesWWT** [hlerenow/hSwiper#15]

**Comment by CharlesWWT** [comment]
点击每个item要传一个index或者name，要更改hswiper-wx里面的内容，就要重新打包上传npm

**Comment by hlerenow** [comment]
目前不支持点击事件的监听，以前没有需求，如果你有时间可以修改后，提交pr，或者周末我抽时间加一个点击事件的分发

**Comment by hlerenow** [comment]
版本已升级2.0.1， 增加了点击事件分发，参见 readme

**Comment by CharlesWWT** [comment]
我在afterViewChange(e)回调里记录了当前index,给hswiper添加了点击事件就能得到当前index的位置了

**Comment by hlerenow** [comment]
Good luck！   ：）

**Comment by Deadpool957** [comment]
hswiper添加了点击事件,是在模板文件中添加点击事件吗？我在模板文件中添加了点击事件，报错VM5225:1 Component "miniprogram_npm/hswiper-wx/index" does not have a method "tapBanner" to handle event "tap".

**Comment by hlerenow** [comment]
@Deadpool957 参考文档 https://github.com/hlerenow/hSwiper-wx/tree/v2.1.0
最下面的onTap事件，提问题请开新的issue的，差点没看到

**Comment by hlerenow** [comment]
参考demo： https://github.com/hlerenow/hSwiper-wx/blob/v2.1.0/example/pages/index/index.wxml
@Deadpool957
