### ISSUE TITLE
安卓滑动不流畅

### ISSUE THREAD

**Issue by WeiBanXian** [hlerenow/hSwiper#2]
在华为1300元的手机上，swiper 横向，每个item是占满屏幕宽度的图片，在item个数达到200、300以上后，手势操作滑动切换的时候，页面会停留在两张图片中间，就是页面没有完全切换到下一页。
能力有限，找不到原因，不知道是js运算的消耗阻塞动画，还是其他原因呢～～

**Comment by WeiBanXian** [comment]
好像是手势响应 touchend 有时候会监听失败

**Comment by hlerenow** [comment]
具体情况不是很清楚，猜测应该是dom元素过多造成的
*  安卓低端机体验本来就不是很好，dom元素过多页面肯定会卡顿，出现不可控的情况
*  页面元素超过200 个，是不是可以考虑优化了
* 优化方案提一种，假设 swiper 只 能显示30（其实3个也行）个元素，当滑到最右边时，更新list（我有提供钩子函数，也就是事件函数） ,将新的 10个 (假设10 个)item 放入list，但是要保持 swiper 里面的元素只有30，所有最左边的 10个 就需要被替换出去，这样页面元素会保持在较少的状态，即使有再多的元素，在低端机上也会有较好的性能（左滑同理），请参考，以后有时间这个组件可能会提供这个优化模式

**Comment by hlerenow** [comment]
浏览器里面UI 渲染是阻塞的 ，也是最耗性能的，所以保持dom元素较少，可以优化一部分浏览器性能，提高页面流畅度

**Comment by AlienC** [comment]
可以设置一直滚动嘛？滚动到最后一张后，自动从第一张滚动？

**Comment by hlerenow** [comment]
目前不支持循环滚动，后续可能会添加
