### ISSUE TITLE
能不能增加往前翻的时候动态添加数据

### ISSUE THREAD

**Issue by musicmanwcj** [hlerenow/hSwiper#4]

**Comment by hlerenow** [comment]
前后翻页钩子我有放置钩子函数，你可以在钩子函数```afterViewChange```里面动态更新 list，可以达到动态添加数据的效果

**Comment by musicmanwcj** [comment]
就是想实现往前翻 翻不完的效果，动态改变list的时候会造成下标不变 导致数据异常

**Comment by hlerenow** [comment]
请问是整个替换了所有数据，还是在原数据之后添加新的数据？

**Comment by musicmanwcj** [comment]
就是日历的效果，往前翻和往后翻都是可以无限的

**Comment by hlerenow** [comment]
我是想问，你代码具体是怎么写的，因为更新的的函数我测试了，是可以正确更新的，但是不知道你怎么使用的更新函数，所以想问下代码怎么写的，方便的话可以贴下相关代码，看看能不能解决，目前是不太会更新这个插件的功能，因为还有工作的事儿，没太多时间，所以如果功能不能达到你想要的效果，目前是没法快速解决的，请见谅

**Comment by musicmanwcj** [comment]
是这样的
比如总共有3个view 我现在在下标为1的view，这时候我往左滑，就是到0，这时候可以调用onFirstView来新增数据，好。
那么第一次加载的是[2017年12月，2018年1月，2018年2月]，指定下标1，此时是2018年1月
当我滑到0时，此时是2017年12月，onFirstView监听到，于是我可以动态增加数据
变成[2017年11月, 2017年12月，2018年1月，2018年2月]
此时下标0，所以显示的是2017年11月而不是我想要的2017年12月
您看是否有这样的问题呢

**Comment by hlerenow** [comment]
插件的数据更新没有问题，是你的使用逻辑有问题，更新前当前的下标本来就是0，数据添加后，0 号位置的数据更新了，0号位的数据本来就是 2017 11 月，而你的当前2017年2月数据其实变成了1号位置的数据，插件的行为是正确的，你可以在更新数据后立即移动到第二个位置，试试

**Comment by musicmanwcj** [comment]
嗯嗯，我已经采用swiper做了循环轮播，再处理数据。如果使用滑动到第二个位置的话会有一个过渡卡顿效果，不是很理想。您的插件如果能增加一个循环轮播的功能就更完美了。

**Comment by hlerenow** [comment]
我更新了```moveViewTo()```函数，可配置过渡无动画效果，可能能解决你的问题(过渡卡顿效果)，有时间你可以试试
```
    console.log('8s后移动试图，无过渡效果');
    swiper.moveViewTo(2, false);
````
参见： exmaple/pages/index/index.js

**Comment by musicmanwcj** [comment]
好的，非常感谢好的，非常感谢
