### ISSUE TITLE
怎么支持纵向啊

### ISSUE THREAD

**Issue by weitemi** [hlerenow/hSwiper#6]
请问下 怎么调整纵向滑动?

**Comment by hlerenow** [comment]
目前暂时不支持纵向模式，因为这个是从之前的项目中抽出来的，当时没有纵向的需求，不过，如果有许多人都有这个需求，之后有时间，我可以增加一个这样的功能。 ：）

**Comment by hlerenow** [comment]
2.0 已经支持纵向滚动，https://github.com/hlerenow/hSwiper
