### ISSUE TITLE
Example导入出错

### ISSUE THREAD

**Issue by Veagau** [hlerenow/hSwiper#7]
![image](https://user-images.githubusercontent.com/28336196/38966993-8e25c09c-43b7-11e8-80e6-1a34639d6434.png)

**Comment by hlerenow** [comment]
你是怎么导入的？，example是一个完整的小程序项目，打开开发者工具，选择小程序项目，选择example，就行了，我这是可以的
![image](https://user-images.githubusercontent.com/13299648/38967146-42dcb324-43b8-11e8-9833-f5a3ee90175f.png)

**Comment by Veagau** [comment]
我是直接选中的那个example文件夹，但是后来弹出来一个代理不安全，会不会有影响

![01](https://user-images.githubusercontent.com/28336196/38967796-415ca42a-43bb-11e8-9d93-240d951459f3.png)
![02](https://user-images.githubusercontent.com/28336196/38967799-443fbdc6-43bb-11e8-999e-0c2b5f796ff2.png)
![image](https://user-images.githubusercontent.com/28336196/38967765-1f43df0c-43bb-11e8-84ed-1cab5c5e137c.png)

**Comment by hlerenow** [comment]
可能是这个原因，因为开发者工具会访问微信的服务器

**Comment by Veagau** [comment]
感谢！是我开了代理下载工具的原因，把代理下载工具关闭后重新导入就没问题了

**Comment by hlerenow** [comment]
Good luck! : )
