### ISSUE TITLE
有api能支持禁止页面触摸滑动么？

### ISSUE THREAD

**Issue by Somnusochi** [hlerenow/hSwiper#8]
有api能控制在当前页面禁止/允许页面左右触摸滑动么？

**Comment by hlerenow** [comment]
目前不支持该功能，你是想只能通过固定的按钮来切换吗？还是说只是在特定的情况下，不想让用户滑动，如果是第二种情况，你可以自己扩展下，用一个view放在swiper 上面，z-index 设置大一点，大于swiper的z-index，这样就不会触发swiper的滑动事件了，然后你可以自己控制是否移除这个view

**Comment by Somnusochi** [comment]
好的，感谢，目前是想通过固定按钮来进行切换

**Comment by hlerenow** [comment]
一样可以通过一个遮挡的view来实现，左右滑动的时候，调用滑动api就行了，嗯嗯
